### ISSUE TITLE
cloning cyclic data structures

### ISSUE THREAD

**Issue by k4b7** [dslomov/ecmascript-structured-clone#9]
Does this handle cyclic data structures?  If so, how?

**Comment by annevk** [comment]
Through the memory map.

**Comment by k4b7** [comment]
It might be good to mention that in the README because other cloning techniques such as `JSON.parse(JSON.stringify(obj))` don't work with cyclic data structures and not everyone will take the time to read through the cloning algorithm.

**Comment by annevk** [comment]
Create a PR?
